version: '3.8'
services:
  djangoapi:
    build: DjangoAPI
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourusername
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - "27017:27017"
