# Generated by Django 4.1.10 on 2023-09-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensorId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('acoustic', 'Acoustic')], max_length=20)),
                ('vendorName', models.CharField(max_length=100)),
                ('vendorEmail', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sensorId', models.CharField(max_length=50)),
                ('readingType', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('acoustic', 'Acoustic')], max_length=20)),
                ('readingValue', models.FloatField()),
                ('readingDate', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=9)),
            ],
        ),
    ]
