# Generated by Django 4.1.10 on 2023-09-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensorId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('acoustic', 'Acoustic')], max_length=20)),
                ('vendorName', models.CharField(max_length=100)),
                ('vendorEmail', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('readingType', models.CharField(max_length=50)),
                ('readingValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('readingDate', models.DateField()),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('sensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingService.sensor')),
            ],
        ),
    ]
