# Generated by Django 4.1.10 on 2023-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
