# Generated by Django 4.1.10 on 2023-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='readingDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='readingType',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('acoustic', 'Acoustic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensorId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='time',
            field=models.CharField(max_length=9),
        ),
    ]
